version: '3.3'

services:
  anaconda:
    build:
      context: .
      dockerfile: ./srv/anaconda/Dockerfile
      args:
        HTTP_PROXY: http://127.0.0.1:7890
        HTTPS_PROXY: https://127.0.0.1:7890
    volumes:
       - ../sourcecode:/opt/sourcecode
       - ./notebooks:/opt/notebooks
    ports:
      - "80:8888"
    command:
      /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root
    tty: true
