version: '3.3'

services:
  anaconda:
    build:
      context: .
      dockerfile: ./srv/anaconda/Dockerfile
      args:
        HTTP_PROXY: http://host.docker.internal:${PROXY_PORT:-1080}
        HTTPS_PROXY: https://host.docker.internal:${PROXY_PORT:-1080}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
       - ../../sourcecode/RAG:/opt/notebooks/sourcecode/RAG
       - ./notebooks:/opt/notebooks/notebooks
    ports:
      - "80:8888"
    command:
      /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root
    tty: true
